### ISSUE TITLE
Platform API

### ISSUE THREAD

**Issue by mtaha1996** [Avidnet/FANIoTAgri#1]
@1995parham please share the platform API  whenever you want

**Comment by 1995parham** [comment]
APIs are ready and their swagger file is accessible from [here](https://github.com/I1820/backend/blob/master/swagger/swagger.yml). Swagger UI is only available in our company local network under the following link:

```
http://192.168.73.3:1994/swagger
```

**Comment by mtaha1996** [comment]
tnx !
